### ISSUE TITLE
not found mlog table for table_name

### ISSUE THREAD

**Issue by heruihong** [alibaba/yugong#26]
我的需求是 Oracle>MySQL 全量+增量同步

遇到报错如下：
  ERROR com.taobao.yugong.common.alarm.LogAlarmService - Alarm:com.taobao.yugong.exception.YuGongException: com.taobao.yugong.exception.YuGongException: not found mlog table for [ZHWLDEV.EB_LOCATION]
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:269)
	at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.taobao.yugong.exception.YuGongException: not found mlog table for [ZHWLDEV.EB_LOCATION]
	at com.taobao.yugong.extractor.oracle.OracleMaterializedIncRecordExtractor.start(OracleMaterializedIncRecordExtractor.java:86)
	at com.taobao.yugong.extractor.oracle.OracleAllRecordExtractor.extract(OracleAllRecordExtractor.java:104)
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:189)
	... 2 more

源库目标库均有CRUD权限 、源库物化视图创建删除权限也给了 

谢谢。。。

**Comment by agapple** [comment]
not found mlog table for [ZHWLDEV.EB_LOCATION]，没建好物化视图的表，可以使用MARK模式手工执行以下看看

**Comment by zilanghuo** [comment]
MARK模式？能否详细说一下吗？按照正常的模式建物化视图，会提示无标识符：SEQUENCE$$，缺失了一个字段。谢谢
