### ISSUE TITLE
Oracle（Database 10g Enterprise Edition Release 10.2.0.4.0 - 64bi）数据同步到MySQL报错

### ISSUE THREAD

**Issue by gjf281** [alibaba/yugong#33]
报错描述：
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select * from (select rowid,OLD_NEW$$,ID,SNAPTIME$$,DMLTYPE$$,CHANGE_VECTOR$$ from MODELHOME.MLOG$_YUGONG_EXAMPLE_ORACL order by sequence$$ asc) where rownum <= ?]; nested exception is java.sql.SQLException: ORA-00904: "SEQUENCE$$": invalid identifier

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:220)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619)
	at com.taobao.yugong.extractor.oracle.OracleMaterializedIncRecordExtractor.getMlogRecord(OracleMaterializedIncRecordExtractor.java:162)
	at com.taobao.yugong.extractor.oracle.OracleMaterializedIncRecordExtractor.extract(OracleMaterializedIncRecordExtractor.java:121)
	at com.taobao.yugong.extractor.oracle.OracleAllRecordExtractor.extract(OracleAllRecordExtractor.java:108)
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:189)
	... 2 more
Caused by: java.sql.SQLException: ORA-00904: "SEQUENCE$$": invalid identifier

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:216)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:810)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1039)
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:850)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1134)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3339)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3384)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.taobao.yugong.extractor.oracle.OracleMaterializedIncRecordExtractor$2.doInPreparedStatement(OracleMaterializedIncRecordExtractor.java:168)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	... 7 more
原因分析：
将MLOG_EXTRACT_FORMAT    修改为 "select rowid,{0} from {1}.{2}  where rownum <= ?" 执行就正常了

查看代码提交记录2016.06.06号的一次提交中，将MLOG_EXTRACT_FORMAT做了修改为"select * from (select rowid,{0} from {1}.{2} order by sequence$$ asc) where rownum <= ?";
该次修改在10.2.0.4.0 Oracle版本上是否存在兼容问题？

**Comment by agapple** [comment]
新版本修改过物化视图的生成策略，可以clear/mark重新生成下物化视图即可

**Comment by gjf281** [comment]
理解
