### ISSUE TITLE
代码错误？ NullPointer Exception

### ISSUE THREAD

**Issue by bash99** [alibaba/yugong#39]
同步时碰到如下错误
2017-01-03 13:59:05.307 [YuGongInstance-JKCITY.HOSPINFO] ERROR com.taobao.yugong.controller.YuGongInstance - retry 1 ,something error happened. caused by java.lang.NullPointerException
        at com.taobao.yugong.common.db.RecordDiffer.diff(RecordDiffer.java:49)
        at com.taobao.yugong.applier.CheckRecordApplier.diff(CheckRecordApplier.java:347)
...

看 CheckRecordApplier.java:347 行
            RecordDiffer.diff(null, record2);

com.taobao.yugong.common.db.RecordDiffer.diff
    public static void diff(Record record1, Record record2) {
        if (record2 == null) {
            diffLogger.info(diffMessage(record1.getSchemaName(),
                record1.getTableName(),
                record1.getPrimaryKeys(),
                "record not found"));
            return;
        }

        if (record1.getColumns().size() > record2.getColumns().size()) {
            diffLogger.info(diffMessage(record1.getSchemaName(),
                record1.getTableName(),
                record1.getPrimaryKeys(),
                "column size is great than target column size"));

            return;
        }

这样的话，如果执行到这个逻辑，必然触发 record1 为 null 的exception?

**Comment by agapple** [comment]
源库record1不应该出现NULL值，能帮忙debug看看具体的内容？

**Comment by bash99** [comment]
@agapple 
这个NULL值是调用时就设定的
            RecordDiffer.diff(null, record2);
CheckRecordApplier.java:347 行

出现情况可能是某次运行中，服务器端增加了字段（可能已经过了字典比较阶段），然后就出现了这个错误。
在mysql增加字段重启后正常。
但是上面的运行路径是不对的，就是不知道怎么出现的。

**Comment by agapple** [comment]
也就是说对源库有一次字段变更操作？

**Comment by bash99** [comment]
@agapple 对，并且没通知到我，因此从库没改。但是如果全新启动的yugong，应该是报字段错误的。

**Comment by agapple** [comment]
好的，这问题我记下，如果你有bugfix代码也可以提交给我
