### ISSUE TITLE
不知道是不是版本问题jdk1.7

### ISSUE THREAD

**Issue by hyper2015** [alibaba/yugong#41]
行业 ：征信行业
QQ 327467030

com.taobao.yugong.exception.YuGongException: com.taobao.yugong.exception.YuGongException: source:com.taobao.yugong.translator.YugongExampleOracleDataTranslator
	at com.taobao.yugong.controller.YuGongController.choseTranslator(YuGongController.java:386)
	at com.taobao.yugong.controller.YuGongController.start(YuGongController.java:173)
	at com.taobao.yugong.YuGongLauncher.main(YuGongLauncher.java:32)
Caused by: com.taobao.yugong.exception.YuGongException: source:com.taobao.yugong.translator.YugongExampleOracleDataTranslator
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:60)
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:48)
	at com.taobao.yugong.controller.YuGongController.buildTranslator(YuGongController.java:408)
	at com.taobao.yugong.controller.YuGongController.choseTranslator(YuGongController.java:384)
	... 2 more
Caused by: com.taobao.yugong.exception.YuGongException: Can't find java compiler , pls check tools.jar
	at com.taobao.yugong.common.utils.compile.JdkCompiler$JdkCompileTask.<init>(JdkCompiler.java:82)
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:53)
	... 5 more

**Comment by hyper2015** [comment]
用户不一致迁移也会失败？

**Comment by hyper2015** [comment]
table[null.T_test001] is not found  这错误是为什么 奇怪了

**Comment by agapple** [comment]
需要用jdk，而不是用jre

**Comment by hyper2015** [comment]
Alarm:com.taobao.yugong.exception.YUGONGException:table[null.T_TEST001] is not found
create table t_test001(id bigint,name varchar(100),age decimal(5));
Oracle 10 到  mysql 5.7.16 
完全没有头绪为什么会出现这样的错误   我起初怀疑线程传目标用户名失败导致？但是没有根据。。。
在测试环境可以 ，但是换了一个测试环境（换的环境软件和配置都一样就是源数据库和目标数据库的版本不一样）就出现上面的告警，数据导入警告。
在log目录产生了一个源数据库用户名.表名的目录
求楼主关注

**Comment by hyper2015** [comment]
我个人觉得 导入跟oracle和mysql版本没有多大区别吧

**Comment by fanzengfeng** [comment]
根版本没有关系，最简单的解决方法 把jdk/lib/tools.jar 复制到 jre/lib 目录下，完美解决。
