### ISSUE TITLE
测试的的时候报错，哪位大神帮忙查一下

### ISSUE THREAD

**Issue by betonothing** [alibaba/yugong#44]
2017-04-07 11:32:04.583 [YuGongInstance-TRANUSR.YUGONG_EXAMPLE_ORACLE] INFO  c.t.y.e.oracle.OracleMaterializedIncRecordExtractor - table[TRANUSR.YUGONG_EXAMPLE_ORACLE] now is CATCH_UP ...
2017-04-07 11:32:04.664 [YuGongInstance-TRANUSR.YUGONG_EXAMPLE_ORACLE] ERROR com.taobao.yugong.controller.YuGongInstance - retry 1 ,something error happened. caused by com.taobao.yugong.exception.YuGongException: table[null.YUGONG_EXAMPLE_ORACLE] is not found
	at com.taobao.yugong.common.db.meta.TableMetaGenerator$1.doInConnection(TableMetaGenerator.java:76)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342)
	at com.taobao.yugong.common.db.meta.TableMetaGenerator.getTableMeta(TableMetaGenerator.java:51)
	at com.taobao.yugong.applier.IncrementRecordApplier.getInsertSqlUnit(IncrementRecordApplier.java:159)
	at com.taobao.yugong.applier.IncrementRecordApplier.getSqlUnit(IncrementRecordApplier.java:138)
	at com.taobao.yugong.applier.IncrementRecordApplier.applyOneByOne(IncrementRecordApplier.java:86)
	at com.taobao.yugong.applier.MultiThreadIncrementRecordApplier.applyBatch0(MultiThreadIncrementRecordApplier.java:240)
	at com.taobao.yugong.applier.MultiThreadIncrementRecordApplier.applyBatch(MultiThreadIncrementRecordApplier.java:175)
	at com.taobao.yugong.applier.MultiThreadIncrementRecordApplier.doApply(MultiThreadIncrementRecordApplier.java:104)
	at com.taobao.yugong.applier.MultiThreadIncrementRecordApplier.apply(MultiThreadIncrementRecordApplier.java:92)
	at com.taobao.yugong.applier.AllRecordApplier.apply(AllRecordApplier.java:60)
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:215)
	at com.taobao.yugong.controller.YuGongInstance$1.run(YuGongInstance.java:145)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hyper2015** [comment]
大神说是你的mysql 大小是敏感的 你关闭大小写敏感试试

**Comment by betonothing** [comment]
我是直接在eclipse里执行的YuGongLauncher的main方法，这样执行找不到转换的类，大神们抽空帮忙看看如何单步调式，非常感谢。

**Comment by agapple** [comment]
你参考源码里的转换类

**Comment by D-T-Y** [comment]
我也碰到这个问题了
![image](https://user-images.githubusercontent.com/21084531/52990978-85947e80-3445-11e9-9751-823fe3466ef2.png)
这行代码说schemaName为null，不清楚哪个地方配置错了
