### ISSUE TITLE
windows启动出现jdk的报错

### ISSUE THREAD

**Issue by ZPLOVEXYH** [alibaba/yugong#64]
2018-03-23 17:51:39.642 [main] ERROR com.taobao.yugong.YuGongLauncher - ## Something goes wrong when starting up the YuGong:
com.taobao.yugong.exception.YuGongException: com.taobao.yugong.exception.YuGongException: source:com.taobao.yugong.translator.YugongExampleOracleDataTranslator
	at com.taobao.yugong.controller.YuGongController.choseTranslator(YuGongController.java:386)
	at com.taobao.yugong.controller.YuGongController.start(YuGongController.java:173)
	at com.taobao.yugong.YuGongLauncher.main(YuGongLauncher.java:32)
Caused by: com.taobao.yugong.exception.YuGongException: source:com.taobao.yugong.translator.YugongExampleOracleDataTranslator
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:60)
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:48)
	at com.taobao.yugong.controller.YuGongController.buildTranslator(YuGongController.java:408)
	at com.taobao.yugong.controller.YuGongController.choseTranslator(YuGongController.java:384)
	... 2 more
Caused by: com.taobao.yugong.exception.YuGongException: Can't find java compiler , pls check tools.jar
	at com.taobao.yugong.common.utils.compile.JdkCompiler$JdkCompileTask.<init>(JdkCompiler.java:82)
	at com.taobao.yugong.common.utils.compile.JdkCompiler.compile(JdkCompiler.java:53)
	... 5 more

**Comment by chenxu89** [comment]
已经设置了设置JAVA_HOME为jdk的路径，还是报这个错误
