### ISSUE TITLE
删除MLOG$_相关表，无法继续同步，重新创建不起作用

### ISSUE THREAD

**Issue by xueling555** [alibaba/yugong#94]
com.taobao.yugong.exception.YuGongException: not found mlog table for [PRE_EGOV.GS_L_XZCF]
at com.taobao.yugong.extractor.oracle.OracleMaterializedIncRecordExtractor.start(OracleMaterializedIncRecordExtractor.java:86)
	at com.taobao.yugong.extractor.oracle.OracleAllRecordExtractor.extract(OracleAllRecordExtractor.java:104)
	at com.taobao.yugong.controller.YuGongInstance$1.processTable(YuGongInstance.java:189)
	... 2 more

**Comment by xueling555** [comment]
解决了，删除项目../conf/positioner目录下对应.dat文件
